type: dev-environment
# The name is optional, if not specified, generated randomly
name: tpu-vscode
# Launches a dev environment to play with TGI
# Refer to Note section in examples/gpus/tpu/README.md for more information about the image.
image: sjbbihan/optimum-tpu:latest

# Required environment variables
env:
  - HUGGING_FACE_HUB_TOKEN
ide: vscode

# Use either spot or on-demand instances
spot_policy: auto
# Uncomment to ensure it doesn't create a new fleet
#creation_policy: reuse

resources:
  gpu: v5litepod-8
