type: object
additionalProperties: false
properties:
  requirements:
    type: string
  python_script:
    type: string
  python:
    type: string
    enum: [ "3.10", "3.9", "3.8", "3.7" ]
  script:
    type: string
  version:
    oneOf:
      - type: string
        enum: [ "3.10", "3.9", "3.8", "3.7" ]
      - type: number
        enum: [ 3.10, 3.9, 3.8, 3.7 ]
  working_dir:
    type: string
  resources:
    type: object
    properties:
      cpu:
        type: integer
      memory:
        type: string
      gpu:
        type: integer
    additionalProperties: false
  environment:
    type: object
    additionalProperties: true
  artifacts:
    type: array
    items:
      type: string
#required:
#  - script