site_name: dstack
#repo_url: https://github.com/dstackai/dstack
#repo_name: dstackai/dstack
#edit_uri: edit/master/docs/
theme:
  name: material
  logo: assets/dstack_notext.png
  favicon: images/dstack_fav_32.ico
  icon:
    repo: fontawesome/brands/github
  font:
    text: Source Sans Pro
    code: IBM Plex Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: lilac
  #      toggle:
  #        icon: material/weather-night
  #        name: Switch to dark mode
  #    - media: "(prefers-color-scheme: dark)"
  #      scheme: slate
  #      primary: black
  #      accent: light blue
  #      toggle:
  #        icon: material/weather-sunny
  #        name: Switch to light mode
  features:
    - toc.integrate
    - navigation.sections
    - navigation.expand
    - navigation.top
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - def_list
  - admonition
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      toc_depth: 2
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
extra:
  homepage: https://dstack.ai
  generator: false
  analytics:
    provider: google
    property: UA-4493451-5
#plugins:
#    - redirects:
#        redirect_maps:
#            'workflows.md': 'define-workflows.md'
nav:
  - Get started:
      - Overview: index.md
      - Quickstart: quickstart.md
  - Basics:
      - Setup: setup.md
      - Workflows: workflows.md
      - Run command:
        - Run workflows: run-workflows.md
        - Run providers: run-providers.md
#      - Runners: runners.md
#      - Custom providers: custom-providers.md
#      - Docker: docker.md
  - Help:
      - Slack community: https://join.slack.com/t/dstackai/shared_invite/zt-xdnsytie-D4qU9BvJP8vkbkHXdi6clQ
      - Issue tracker: https://github.com/dstackai/dstack/issues