# Project information
site_name: dstack
site_url: https://docs.dstack.ai
site_author: Andrey Cheptsov
site_description: >-
  dstack is a command-line utility to run ML workflows in the cloud,
  while keeping your workflows highly reproducible.

# Repository
repo_url: https://github.com/dstackai/dstack
repo_name: dstackai/dstack
edit_uri: edit/master/docs/

#Copyright
copyright: © 2022 dstack GmbH

# Configuration
theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/dstack_notext.svg
  favicon: images/dstack_fav_32.ico
  icon:
    repo: fontawesome/brands/github
  font:
    text: Source Sans Pro
    code: IBM Plex Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: lilac
  #        toggle:
  #          icon: material/weather-night
  #          name: Switch to dark mode
  #      - media: "(prefers-color-scheme: dark)"
  #        scheme: slate
  #        primary: black
  #        accent: light blue
  #        toggle:
  #          icon: material/weather-sunny
  #          name: Switch to light mode
  features:
#    - navigation.indexes
    - navigation.tabs
#    - navigation.instant
    #    - toc.integrate
    - navigation.sections
    - navigation.expand
    - navigation.top
    - announce.dismiss

# Plugins
plugins:
  - social:
      cards_color:
        fill: "#fefeff"
      cards_font: Roboto
  - search
#  - redirects:
#      redirect_maps:
#        'index.md': 'quickstart/index.md'

# Extensions
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - def_list
  - admonition
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      toc_depth: 2
  - attr_list
  - md_in_html

# Customization
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
extra:
  homepage: /
  generator: false
  analytics:
    provider: google
    property: UA-4493451-5
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dstackai/dstack
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/dstack/
    - icon: fontawesome/brands/slack
      link: https://join.slack.com/t/dstackai/shared_invite/zt-xdnsytie-D4qU9BvJP8vkbkHXdi6clQ
    - icon: material/rss
      link: https://mlopsfluff.dstack.ai
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/dstackai

# Page tree
nav:
  - Guide:
    - Introduction:
        - Overview: index.md
        - What is dstack?: what-is-dstack.md
        - Use cases: use-cases.md
    - Getting started:
        - Installation: installation.md
        - "Tutorial: Quickstart": tutorials/quickstart.md
    - Examples:
        - Hello, world: examples/hello.md
        - Python: examples/python.md
        - Resources: examples/resources.md
        - Artifacts: examples/artifacts.md
        - Deps: examples/deps.md
        - Environment variables: examples/env.md
        - Apps: examples/apps.md
        - Secrets: examples/secrets.md
        - Dev environments: examples/devs.md
    - Other docs:
      - FAQs: faq.md
  - Reference:
      - CLI:
        - dstack: reference/cli/index.md
        - dstack run: reference/cli/run.md
        - dstack ps: reference/cli/ps.md
        - dstack stop: reference/cli/stop.md
        - dstack logs: reference/cli/logs.md
        - dstack artifacts: reference/cli/artifacts.md
        - dstack tags: reference/cli/tags.md
        - dstack init: reference/cli/init.md
        - dstack config: reference/cli/config.md
        - dstack secrets: reference/cli/secrets.md
        - dstack rm: reference/cli/rm.md
      - Providers:
#          - Introduction: reference/workflows/index.md
          - bash: reference/providers/bash.md
          - code: reference/providers/code.md
          - lab: reference/providers/lab.md
          - notebook: reference/providers/notebook.md
          - docker: reference/providers/docker.md
  #        - torchrun: reference/workflows/torchrun.md
  - Community: community.md