site_name: dstack
repo_url: https://github.com/dstackai/dstack
repo_name: dstackai/dstack
site_description: >-
  dstack is an open-source CLI that allow to define ML workflows as code and run them on cloud. 
  It provisions infrastructure and manages data automatically.
edit_uri: edit/master/docs/
copyright: © 2022 dstack GmbH
theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/dstack_notext.png
  favicon: images/dstack_fav_32.ico
  icon:
    repo: fontawesome/brands/github
  font:
    text: Source Sans Pro
    code: IBM Plex Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: lilac
  #        toggle:
  #          icon: material/weather-night
  #          name: Switch to dark mode
  #      - media: "(prefers-color-scheme: dark)"
  #        scheme: slate
  #        primary: black
  #        accent: light blue
  #        toggle:
  #          icon: material/weather-sunny
  #          name: Switch to light mode
  features:
    - navigation.indexes
    #    - toc.integrate
    - navigation.sections
    #    - navigation.expand
    - navigation.top
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - def_list
  - admonition
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      toc_depth: 2
  - attr_list
  - md_in_html
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
extra:
  homepage: https://dstack.ai
  generator: false
  analytics:
    provider: google
    property: UA-4493451-5
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dstackai/dstack
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/dstackai
    - icon: fontawesome/brands/slack
      link: https://join.slack.com/t/dstackai/shared_invite/zt-xdnsytie-D4qU9BvJP8vkbkHXdi6clQ
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/dstackai
nav:
  - Get started:
      - index.md
      - Intro: index.md
      - Concepts: concepts.md
      - Installation: installation.md
      - Quickstart: quickstart.md
      - Examples: examples/index.md
  - Reference:
      - Workflows: workflows/overview.md
      - Providers:
        - providers/index.md
        - bash: providers/bash.md
        - code: providers/code.md
        - lab: providers/lab.md
        - notebook: providers/notebook.md
        - docker: providers/docker.md
#        - torchrun: providers/torchrun.md
      - CLI:
        - cli/index.md
        - run: cli/run.md
        - ps: cli/ps.md
        - stop: cli/stop.md
        - logs: cli/logs.md
        - artifacts: cli/artifacts.md
        - tags: cli/tags.md
        - init: cli/init.md
        - config: cli/config.md
        - secrets: cli/secrets.md
        - delete: cli/delete.md
  - Help:
      - Slack chat: https://join.slack.com/t/dstackai/shared_invite/zt-xdnsytie-D4qU9BvJP8vkbkHXdi6clQ
      - GitHub issues: https://github.com/dstackai/dstack/issues
