site_name: dstack
repo_url: https://github.com/dstackai/dstack
repo_name: dstackai/dstack
site_description: >-
  dstack is an open-source CLI that allow to define ML workflows as code and run them on cloud. 
  It provisions infrastructure and manages data automatically.
edit_uri: edit/master/docs/
copyright: © 2022 dstack GmbH
theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/logo.svg
  favicon: images/dstack_fav_32.ico
  icon:
    repo: fontawesome/brands/github
  font:
    text: Source Sans Pro
    code: IBM Plex Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: lilac
  #        toggle:
  #          icon: material/weather-night
  #          name: Switch to dark mode
  #      - media: "(prefers-color-scheme: dark)"
  #        scheme: slate
  #        primary: black
  #        accent: light blue
  #        toggle:
  #          icon: material/weather-sunny
  #          name: Switch to light mode
  features:
#    - navigation.indexes
    - navigation.tabs
#    - navigation.instant
    #    - toc.integrate
    - navigation.sections
    - navigation.expand
    - navigation.top
    - announce.dismiss
#plugins:
#  - search
#  - redirects:
#      redirect_maps:
#        'index.md': 'quickstart/index.md'
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - def_list
  - admonition
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      toc_depth: 2
  - attr_list
  - md_in_html
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
extra:
  homepage: /
  generator: false
  analytics:
    provider: google
    property: UA-4493451-5
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dstackai/dstack
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/dstack/
    - icon: fontawesome/brands/slack
      link: https://join.slack.com/t/dstackai/shared_invite/zt-xdnsytie-D4qU9BvJP8vkbkHXdi6clQ
    - icon: simple/substack
      link: https://mlopsfluff.dstack.ai
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/dstackai
nav:
  - Quickstart:
    - Getting started:
        - What is dstack?: index.md
        - Installation: installation.md
#        - Concepts: concepts.md
        - "Tutorial: First steps": tutorials/first-steps.md
    - Examples:
        - Hello, world: examples/hello.md
        - Python: examples/python.md
        - Resources: examples/resources.md
        - Artifacts: examples/artifacts.md
        - Deps: examples/deps.md
        - Environment variables: examples/env.md
        - Apps: examples/apps.md
        - Secrets: examples/secrets.md
        - Dev environments: examples/devs.md
    - Other docs:
      - FAQs: faq.md
#        - Cheat sheet: other/cheatsheet.md
  - Reference:
#      - Examples: reference/examples/index.md
      - CLI:
        - dstack: reference/cli/index.md
        - dstack run: reference/cli/run.md
        - dstack ps: reference/cli/ps.md
        - dstack stop: reference/cli/stop.md
        - dstack logs: reference/cli/logs.md
        - dstack artifacts: reference/cli/artifacts.md
        - dstack tags: reference/cli/tags.md
        - dstack init: reference/cli/init.md
        - dstack config: reference/cli/config.md
        - dstack secrets: reference/cli/secrets.md
        - dstack delete: reference/cli/delete.md
      - Providers:
#          - Introduction: reference/workflows/index.md
          - bash: reference/providers/bash.md
          - code: reference/providers/code.md
          - lab: reference/providers/lab.md
          - notebook: reference/providers/notebook.md
          - docker: reference/providers/docker.md
  #        - torchrun: reference/workflows/torchrun.md
  - Community: community.md