site_name: dstack
repo_url: https://github.com/dstackai/dstack
repo_name: dstackai/dstack
site_description: >-
  dstack is an open-source CLI that allow to define ML workflows as code and run them on cloud. 
  It provisions infrastructure and manages data automatically.
edit_uri: edit/master/docs/
copyright: © 2022 dstack GmbH
theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/logo.svg
  favicon: images/dstack_fav_32.ico
  icon:
    repo: fontawesome/brands/github
  font:
    text: Source Sans Pro
    code: IBM Plex Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: lilac
  #        toggle:
  #          icon: material/weather-night
  #          name: Switch to dark mode
  #      - media: "(prefers-color-scheme: dark)"
  #        scheme: slate
  #        primary: black
  #        accent: light blue
  #        toggle:
  #          icon: material/weather-sunny
  #          name: Switch to light mode
  features:
#    - navigation.indexes
    - navigation.tabs
    - navigation.instant
    #    - toc.integrate
    - navigation.sections
    - navigation.expand
    - navigation.top
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - def_list
  - admonition
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      toc_depth: 2
  - attr_list
  - md_in_html
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
extra:
  homepage: /
  generator: false
  analytics:
    provider: google
    property: UA-4493451-5
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dstackai/dstack
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/dstackai
    - icon: fontawesome/brands/slack
      link: https://join.slack.com/t/dstackai/shared_invite/zt-xdnsytie-D4qU9BvJP8vkbkHXdi6clQ
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/dstackai
nav:
  - Guide:
    - Getting started:
        - Introduction: index.md
        - Concepts: concepts.md
        - Installation: installation.md
        - Quickstart: quickstart.md
  - Reference:
#      - Examples: reference/examples/index.md
      - CLI:
        - Introduction: reference/cli/index.md
        - run: reference/cli/run.md
        - ps: reference/cli/ps.md
        - stop: reference/cli/stop.md
        - logs: reference/cli/logs.md
        - artifacts: reference/cli/artifacts.md
        - tags: reference/cli/tags.md
        - init: reference/cli/init.md
        - config: reference/cli/config.md
        - secrets: reference/cli/secrets.md
        - delete: reference/cli/delete.md
      - Workflows:
          - Introduction: reference/workflows/index.md
          - bash: reference/workflows/bash.md
          - code: reference/workflows/code.md
          - lab: reference/workflows/lab.md
          - notebook: reference/workflows/notebook.md
          - docker: reference/workflows/docker.md
  #        - torchrun: reference/workflows/torchrun.md
