type: dev-environment
name: tpu-vscode-llama

# If `image` is not specified, dstack uses its default image
python: "3.11"


# Required environment variables
env:
  - HUGGING_FACE_HUB_TOKEN

# Refer to Note section in README.md for more information about the optimum-tpu repository.
# Uncomment if you want the environment to be pre-installed
init:
  - git clone https://github.com/Bihan/optimum-tpu.git
  - mkdir -p optimum-tpu/examples/custom/
#  - cp examples/fine-tuning/tpu/llama/train_sft.py optimum-tpu/examples/custom/train_sft.py
#  - cp examples/fine-tuning/tpu/llama/config_sft.yaml optimum-tpu/examples/custom/config_sft.yaml
#  - cd optimum-tpu
#  - pip install -e . -f https://storage.googleapis.com/libtpu-releases/index.html
#  - pip install trl peft
#  - pip install datasets evaluate
#  - pip install accelerate>=0.21.0

ide: vscode

spot_policy: auto

resources:
  gpu: tpu-v5litepod-8