type: dev-environment
name: tpu-vscode-llama

# If `image` is not specified, dstack uses its default image
python: "3.11"


# Required environment variables
env:
  - HUGGING_FACE_HUB_TOKEN

# Refer to Note section in README.md for more information about the optimum-tpu repository.
# Uncomment if you want the environment to be pre-installed
#init:
#  - git clone https://github.com/Bihan/optimum-tpu.git
#  - mkdir -p optimum-tpu/examples/custom/
#  - cp examples/fine-tuning/tpu/llama/train.py optimum-tpu/examples/custom/train.py
#  - cp examples/fine-tuning/tpu/llama/config.yaml optimum-tpu/examples/custom/config.yaml
#  - cd optimum-tpu
#  - pip install -e . -f https://storage.googleapis.com/libtpu-releases/index.html
#  - pip install datasets evaluate
#  - pip install accelerate -U

ide: vscode

spot_policy: auto

resources:
  gpu: v5litepod-8