type: task
name: tpu-train-llama

python: "3.11"

env:
  - HUGGING_FACE_HUB_TOKEN

# Refer to Note section in README.md for more information about the optimum-tpu repository.
commands:
  - git clone https://github.com/Bihan/optimum-tpu.git
  - mkdir -p optimum-tpu/examples/custom/
  - cp examples/fine-tuning/tpu/llama/train.py optimum-tpu/examples/custom/train.py
  - cp examples/fine-tuning/tpu/llama/config.yaml optimum-tpu/examples/custom/config.yaml
  - cd optimum-tpu
  - pip install -e . -f https://storage.googleapis.com/libtpu-releases/index.html
  - pip install datasets evaluate
  - pip install accelerate -U
  - python examples/custom/train.py examples/custom/config.yaml


ports:
  - 6006

resources:
  gpu: tpu-v5litepod-8