type: task
# Runs HuggingFace alignment recipe using multiple nodes

nodes: 2

python: 3.11
env:
  - HF_TOKEN
  - WANDB_API_KEY
  - WANDB_ENTITY
  - WANDB_PROJECT
  - HF_HUB_ENABLE_HF_TRANSFER=1
commands:
  - conda install cuda
  - git clone https://github.com/huggingface/alignment-handbook.git
  - cd alignment-handbook
  - pip install -e .
  - pip install wandb packaging ninja
  - pip install flash-attn --no-build-isolation
  - accelerate launch
    --config_file recipes/accelerate_configs/fsdp_multi_node.yaml
    --main_process_ip=$DSTACK_MASTER_NODE_IP
    --main_process_port=8008
    --machine_rank=$DSTACK_NODE_RANK
    --num_processes=$((DSTACK_NODES_NUM * DSTACK_GPUS_PER_NODE))
    --num_machines=$DSTACK_NODES_NUM
    ./scripts/run_sft.py recipes/starchat2-15b/sft/config_v0.1.yaml

resources:
  gpu:
    name: A100
    memory: 80GB
    count: 4
  disk: 150GB
