type: dev-environment
name: tpu-vscode-gemma

# If `image` is not specified, dstack uses its default image
python: "3.11"


# Required environment variables
env:
  - HUGGING_FACE_HUB_TOKEN

# Uncomment if you want the environment to be pre-installed
#init:
#  - git clone https://github.com/huggingface/optimum-tpu.git
#  - mkdir -p optimum-tpu/examples/custom/
#  - cp examples/fine-tuning/tpu/gemma/train.py optimum-tpu/examples/custom/train.py
#  - cp examples/fine-tuning/tpu/gemma/config.yaml optimum-tpu/examples/custom/config.yaml
#  - cd optimum-tpu
#  - pip install -e . -f https://storage.googleapis.com/libtpu-releases/index.html
#  - pip install trl peft

ide: vscode

spot_policy: auto

resources:
  gpu: v5litepod-8