name: Build

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  cli-test-master:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
        python-version: [ 3.6, 3.7, 3.8, 3.9 ]
    defaults:
      run:
        working-directory: src
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with unittest
        run: |
          python -m unittest discover tests -t .

  build-dashboard-master:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dashboard
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install packages
        run: npm install
      - name: Build dist
        run: npm run build-host
      - name: Upload dist
        uses: actions/upload-artifact@v1
        with:
          name: dashboard-dist
          path: dashboard/build

  cli-upload-master:
    runs-on: ubuntu-latest
    needs:
     - cli-test-master
     - build-dashboard-master
    defaults:
      run:
        working-directory: src
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Download dashboard dist
        uses: actions/download-artifact@v1
        with:
          name: dashboard-dist
      - name: Copy dashboard dist
        run: |
          cp -a ../dashboard-dist/** dstack/dashboard/statics
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install wheel twine
      - name: Upload pip package
        run: |
          VERSION=$((${{ github.run_number }} + 150))
          echo "__version__ = \"$VERSION\"" > dstack/version.py
          echo "__is_release__ = False" >> dstack/version.py
          cp ../README.md .
          python setup.py sdist bdist_wheel
          python -m twine upload --repository testpypi --username ${{ secrets.TESTPYPI_USERNAME }} --password ${{ secrets.TESTPYPI_PASSWORD }} dist/*

  runner-test-master:
    defaults:
      run:
        working-directory: runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Test
        run: |
          go version
          go fmt $(go list ./... | grep -v /vendor/)
          go vet $(go list ./... | grep -v /vendor/)
          go test -race $(go list ./... | grep -v /vendor/)

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.29
          args: --issues-exit-code=0

  runner-compile-master:
    defaults:
      run:
        working-directory: runner
    env:
      REPO_NAME: github.com/dstackai/dstack
    strategy:
      matrix:
        include:
          - {goos: "linux", goarch: "386", runson: "ubuntu-latest"}
          - {goos: "linux", goarch: "amd64", runson: "ubuntu-latest"}
          - {goos: "windows", goarch: "386", runson: "ubuntu-latest"}
          - {goos: "windows", goarch: "amd64", runson: "ubuntu-latest"}
          - {goos: "darwin", goarch: "amd64", runson: "macos-latest"}
          - {goos: "darwin", goarch: "arm64", runson: "macos-latest"}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          ACTIONSOS: ${{ matrix.runson }}
        run: |
          go build -ldflags "-X '${REPO_NAME}/runner/version.Version=${{ github.run_number }}' -X '${REPO_NAME}/runner/pkg/log.CloudLog=true' -extldflags '-static'" -o dstack-runner-${{ matrix.goos }}-${{ matrix.goarch }}

      - uses: actions/upload-artifact@v2
        with:
          name: dstack-runner-${{ matrix.goos }}-${{ matrix.goarch }}
          path: runner/dstack-runner-${{ matrix.goos }}-${{ matrix.goarch }}
  runner-upload-master:
    defaults:
      run:
        working-directory: runner
    needs: [ runner-compile-master ]
    strategy:
      matrix:
        include:
          - {goos: "linux", goarch: "386", runson: "ubuntu-latest"}
          - {goos: "linux", goarch: "amd64", runson: "ubuntu-latest"}
          - {goos: "windows", goarch: "386", runson: "ubuntu-latest"}
          - {goos: "windows", goarch: "amd64", runson: "ubuntu-latest"}
          - {goos: "darwin", goarch: "amd64", runson: "macos-latest"}
          - {goos: "darwin", goarch: "arm64", runson: "macos-latest"}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install AWS
        run:  pip install awscli
      - name: Download Runner
        uses: actions/download-artifact@v1
        with:
          name: dstack-runner-${{ matrix.goos }}-${{ matrix.goarch }}
      - name: Upload to S3
        run: |
          aws s3 cp dstack-runner-${{ matrix.goos }}-${{ matrix.goarch }} "s3://dstack-runner-downloads-stgn/${{ github.run_number }}/binaries/dstack-runner-${{ matrix.goos }}-${{ matrix.goarch }}" --acl public-read
          aws s3 cp dstack-runner-${{ matrix.goos }}-${{ matrix.goarch }} "s3://dstack-runner-downloads-stgn/latest/binaries/dstack-runner-${{ matrix.goos }}-${{ matrix.goarch }}" --acl public-read
  ami-build:
    defaults:
      run:
        working-directory: runner
    needs: [ runner-upload-master ]
    strategy:
      matrix:
        variants: [ ami-without-cuda, ami-cuda ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download packer
        run: |
          wget https://releases.hashicorp.com/packer/1.8.0/packer_1.8.0_linux_amd64.zip
          unzip packer_1.8.0_linux_amd64.zip
          chmod +x packer
          cp -R ami/packer/* .
      - name: Run packer
        run: ./packer build -var build_id=${{ github.run_number }} ${{ matrix.variants }}.json
