name: Release

on:
  create:
    tags:
      - '*'

jobs:
  cli-test-tag:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
        python-version: [ 3.6, 3.7, 3.8, 3.9 ]
    defaults:
      run:
        working-directory: ./cli
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with unittest
        run: |
          python -m unittest discover tests -t .

  build-dashboard-tag:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dashboard
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install packages
        run: npm install
      - name: Build dist
        run: npm run build-host
      - name: Upload dist
        uses: actions/upload-artifact@v1
        with:
          name: dashboard-dist
          path: dashboard/build

  cli-upload-tag:
    runs-on: ubuntu-latest
    needs:
      - cli-test-tag
      - build-dashboard-tag
    defaults:
      run:
        working-directory: cli
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Download dashboard dist
        uses: actions/download-artifact@v1
        with:
          name: dashboard-dist
      - name: Copy dashboard dist
        run: |
          cp -a ../dashboard-dist/** dstack/dashboard/statics
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install wheel twine
      - name: Upload pip package
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "__version__ = \"$VERSION\"" > dstack/version.py
          echo "__is_release__ = True" >> dstack/version.py
          cp ../README.md .
          python setup.py sdist bdist_wheel
          python -m twine upload --repository pypi --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }} dist/*
